//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Trade
    {
        public int ID { get; set; }
        public int RieltorID { get; set; }
        public Nullable<int> FlatID { get; set; }
        public Nullable<int> HouseID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public System.DateTime DateTrade { get; set; }
        public decimal Amount { get; set; }
        public decimal RieltorPart { get; set; }
        public string Object 
        {
            get 
            {
                if(FlatID != null) 
                {
                    return $"Квартира, {Flat.Addres}";
                }
                else if (HouseID != null && House != null)
                {
                    return $"Дом, {House.Addres}";
                }
                else if (RegionID != null && Region != null)
                {
                    return $"Участок, {Region.Addres}";
                }
                else
                {
                    return "Объект недвижимости не выбран";
                }
            }
        } 

        public virtual Flat Flat { get; set; }
        public virtual House House { get; set; }
        public virtual Region Region { get; set; }
        public virtual Rieltor Rieltor { get; set; }
    }
}
