//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int ID { get; set; }
        public int RieltorID { get; set; }
        public Nullable<int> FlatID { get; set; }
        public Nullable<int> HouseID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public System.DateTime DateTrade { get; set; }
        public decimal Amount { get; set; }
        public decimal RieltorPart { get; set; }

        public string Object
        {
            get
            {
                if (FlatID != null) // Если выбран объект типа "Квартира"
                {
                    return $"Квартира, {Flat.Addres}"; // Возвращает адрес квартиры
                }
                else if (HouseID != null && House != null) // Если выбран объект типа "Дом"
                {
                    return $"Дом, {House.Addres}"; // Возвращает адрес дома
                }
                else if (RegionID != null && Region != null) // Если выбран объект типа "Участок"
                {
                    return $"Участок, {Region.Addres}"; // Возвращает адрес участка
                }
                else // Если объект не выбран
                {
                    return "Объект недвижимости не выбран"; // Возвращает сообщение об отсутствии выбора
                }
            }
        }

        public virtual Flat Flat { get; set; }
        public virtual House House { get; set; }
        public virtual Region Region { get; set; }
        public virtual Rieltor Rieltor { get; set; }
    }
}
